### ISSUE TITLE
[FR]:Ability to define how many C8000v to deploy and in which region

### ISSUE THREAD

**Issue by jbarozet** [cisco-open/ansible-collection-sdwan#3]
### Please describe the problem

The current behavior is to take all C8000v UUIDs from the PnP portal and deploy them in the AWS region configured in the config file.

### Please describe the solution you'd like

Would be great to specify **the number** of C8000v we actually want to deploy (it's going to be a subset of all UUIDs available) and to **configure the region** in which we want each C8000v to be deployed. Ideally a yaml file to describe the config would be easier. Something like:

```yaml
wan_edges:
  c8000v-01:
    infra:
      provider: "aws"
      region: "eu-west-1"
      image_id: "ami-09db869a0fe225bd4e"
      instance_type: "c5n.large"
      sw_version: "17.12.01a"
      sdwan_model: vedge-C8000V
      sdwan_uuid: "C8K-F6D3B492-ECCA-BA56-93DB-5AA42DF658DB" <-- optional
    config:
      site_id: 101
      system_ip: "1.1.1.4"
      cidr: "10.128.4.0/23"
  c8000v-02:
    infra:
      provider: "aws"
      region: "us-east-1"
      image_id: "ami-09cd769a0fe225bd4e"
      instance_type: "c5n.large"
      sw_version: "17.12.01a"
      sdwan_model: vedge-C8000V
      sdwan_uuid: "C8K-F6B5B282-EAAB-BC43-93DB-2AA42DFE58DB" <-- optional
    config:
      site_id: 102
      system_ip: "1.1.1.6"
      cidr: "10.128.6.0/23"

```
